### ISSUE TITLE
-k option is broken

### ISSUE THREAD

**Issue by jvigne** [applidium/ad_localize#27]
When the file is downloaded, its mime type is application/octet-stream instead of a csv mime type. This type is not included in [CSV_CONTENT_TYPES](https://github.com/applidium/ad_localize/blob/develop/lib/ad_localize/csv_file_manager.rb#L3). Therefore we get an error `<sheet_id>.csv is not a csv`.

Quick fix : add application/octet-stream to CSV_CONTENT_TYPES

**Comment by felginep** [comment]
In fact the `-k` option is not broken. The issue here is that we need to make sure _Allow external access_ is on in sharing options.
