### ISSUE TITLE
Ajouter les commentaires sur Android également

### ISSUE THREAD

**Issue by jvigne** [applidium/ad_localize#3]
Dans le script ADLocalize, il est possible de faire figurer des commentaires sur iOS comme par exemple :

| key | fr | comment fr | en | comment en |
--|--|--|--|--|
player_time_live | Live | bypass-unused-error | Live | bypass-unused-error

Cela donne à l'export :

`"player_time_live" = "Live"; // bypass-unused-error`

on voudrait qu'ils apparaissent aussi dans le xml Android

`<string name="player_time_live">"Live"</string> <!-- bypass-unused-error -->`

**Comment by jvigne** [comment]
@claireduf le générateur d'xml que l'on utilise permet difficilement d'avoir le commentaire sur la même ligne. Je vais l'ajouter au dessus, ça te convient?
```
<!-- bypass-unused-error -->
<string name="player_time_live">"Live"</string>
```

**Comment by claireduf** [comment]
yes, no problem

**Comment by jvigne** [comment]
Fixed by 76f4925
@claireduf can you validate the behavior?
