### ISSUE TITLE
--only option seems to be ignored on 4.0.3

### ISSUE THREAD

**Issue by vincentbrison** [applidium/ad_localize#55]
After updating from ad_localize `3.5.0` to `4.0.3` I noticed option `--only -o` seems not to work anymore.
Using command like:
```
bundle exec ad_localize -o android -k <my-spreadsheet-key>
```
will generate `exports/android` but also`exports/ios|json|properties|yml` when it should only generate `exports/android`. This is not a blocking issue has I can move / delete these extra folder easily after import wordings.

**Comment by felginep** [comment]
+1 This is blocking
