### ISSUE TITLE
Gestion de caractères spécifiques

### ISSUE THREAD

**Issue by Loruki** [applidium/ad_localize#8]
When I use the script, I got some sonar errors for some string in ukrainian : 
  
Format string '`s_deficiency_question_title`' is not a valid format string so it should not be passed to `String.format`

  <string name="s_deficiency_question_title">"Вибрати потенційний дефіцит"</string>

**Comment by Nooba** [comment]
Hello @Loruki 

I don't see any format specifier in your ukrainian string. Thus it should use String.init instead of String.format. I believe this is the reason you are triggering a sonar warning, not the script itself.
