### ISSUE TITLE
Handle every string formatter types (for Android)

### ISSUE THREAD

**Issue by sjcqs** [applidium/ad_localize#9]
Expected: 
Every entered string formatter types should be retrieved inside the `string.xml` file.

Behavior: 
To ensure compatibility with iOS the only type supported is `$@`. The opposite should be done every type should be written to Android `string.xml` as it is and to '$@' on iOS. 

(ex: '$d', '$f', '$x', etc)

**Comment by jvigne** [comment]
@Nooba do you know why we made the decision to infer Android formats from ios formats?

**Comment by acq** [comment]
I know this one!
In iOS, we could still have %s in rare cases (C-strings vs NSString).
Converting Android's %s to always iOS's %@ would then be the wrong behavior.

Instead, with the current solution, iOS's %@ is converted to Android's %s and iOS's %s is left as is.

**Comment by Nooba** [comment]
Actually I don't believe %@ is the only type supported. It does work with %f, %d and others, but I think these are the same on both platforms, thus it "should" work.
What would be the missing formatters for android? @sjcqs

**Comment by sjcqs** [comment]
@jvigne  this can be closed
